### ISSUE TITLE
how to change 3d object in this widget?

### ISSUE THREAD

**Issue by ebrahimimasod** [zesage/flutter_cube#10]
Hi !
Thank you for amazing plugin.
how  i can change obj file in cube widget when showing model ?
i think  method setState can not working in this widget.

**Comment by zesage** [comment]
Remove the obj and than add a new obj.
scene.world.remove(obj1);
scene.world.add(obj2)

MasoodEbrahimi <notifications@github.com> 于2020年6月28日周日 下午1:48写道：
