### ISSUE TITLE
Scene lighting support?

### ISSUE THREAD

**Issue by IgnaceMaes** [zesage/flutter_cube#13]
Are there any plans to release a new version of the library to pub.dev with lighting support available?

I would like to use it in my project but the latest published package version (0.0.5) does not include it yet, though it is in the master branch of the repository.

**Comment by zesage** [comment]
0.0.6 has been published to pub.dev

**Comment by IgnaceMaes** [comment]
Thank you for updating the package!

Much appreciated for all the work you've put into this library 🙂
