### ISSUE TITLE
something is wrong

### ISSUE THREAD

**Issue by mohamadkenway** [zesage/flutter_cube#3]
onSceneCreated: (Scene scene) {
            scene.world.add(Object(fileName: 'assets/cube/cube.obj'));
          },
 not working !!!

**Comment by zesage** [comment]
Try the following code:
onSceneCreated: (Scene scene) {
scene.world.add(Object(fileName: 'assets/cube/cube.obj'));
scene.updateTexture();
},

**Comment by zesage** [comment]
fixed by https://github.com/zesage/flutter_cube/commit/7b0292e6c8092bbb20dfedf9a7f1f63ba9dacce0
